var lang = {
    addNew: "Add New",
    after: "After",
    alignment: "Alignment",
    altText: "Alt text",
    alwaysResponsive: "Always responsive",
    badgepill: "Badge pill",
    before: "Before",
    bodyHtml: "Body HTML",
    border: "Border",
    bordered: "Bordered",
    borderless: "Borderless",
    bottom: "Bottom",
    browse: "Browse",
    button: "Button",
    buttonSize: "Button size",
    buttonStyle: "Button style",
    cancel: "Cancel",
    caption: "Caption",
    cardStyle: "Card style",
    cells: "Cells",
    center: "Center",
    choose: "Choose",
    closeButton: "Close button",
    code: "Code",
    container: "Container",
    current: "Current",
    custom: "Custom",
    customColor: "Pick a color",
    customSize: "Custom size",
    dark: "Dark",
    default: "Default",
    disabled: "Disabled",
    disabledWarning: "Disabled elements will not be editable in TinyMce editor",
    dismissable: "Dismissable",
    flip: "Flip",
    flipBoth: "Flip both",
    flipHorizontal: "Flip horizontal",
    flipVertical: "Flip vertical",
    floatLeft: "Float left",
    floatRight: "Float right",
    fluidContainer: "Fluid container (width 100%)",
    footer: "Footer",
    footerHtml: "Footer HTML",
    header: "Header",
    headerHtml: "Header HTML",
    horizontalHeader: "Horizontal header",
    icon: "Icon",
    iconColor: "Icon color",
    icons: "Icons",
    iconSize: "Icon size",
    iconStyle: "Icon style",
    image: "Image",
    imageOverlay: "Image overlay",
    imageOverlayHtml: "Image overlay HTML",
    imageStyle: "Image style",
    inputWarning: "Icons are not available with <em>input</em> tags",
    insert: "Insert",
    insertAfterContainer: "Insert after the current container",
    insertAfterRow: "Insert after the current row",
    insertBeforeContainer: "Insert before the current container",
    insertBeforeRow: "Insert before the current row",
    insertBeginning: "Insert at the beginning of the document",
    insertBeginningContainer: "Insert at the beginning of the current container",
    insertCursorPosition: "Insert at the cursor position",
    insertEnd: "Insert at the end of the document",
    insertEndContainer: "Insert at the end of the current container",
    items: "Items",
    large: "Large",
    largeRadius: "Large radius",
    left: "Left",
    light: "Light",
    link: "Link",
    medium: "Medium",
    mediumRadius: "Medium radius",
    no: "No",
    noContainer: "No container",
    normalContainer: "Normal container",
    options: "Options",
    others: "Others",
    outline: "Outline",
    page: "Page",
    pages: "Pages",
    paginationfirst: "First",
    paginationlast: "Last",
    position: "Position",
    preview: "Preview",
    pulse: "Pulse",
    removeImage: "Remove image",
    reset: "Reset",
    responsive: "Responsive",
    responsiveLg: "Responsive on Large and XL screens",
    responsiveMd: "Responsive on Medium screens and larger",
    responsiveSm: "Responsive on Small screens and larger",
    responsiveXl: "Responsive on XL screens",
    right: "Right",
    rotate: "Rotate",
    roundedCircle: "Rounded circle",
    roundedPill: "Rounded pill",
    rowsCols: "Rows / Cols",
    size: "Size",
    small: "Small",
    smallRadius: "Small radius",
    snippets: "Snippets",
    spin: "Spin",
    structure: "Structure",
    style: "Style",
    submit: "Submit",
    tableDark: "Table dark",
    tableEditDisabledInfo: "The editing of the table structure is disabled. Rows and columns can be edited directly in tinyMce.",
    tableHover: "Table hover",
    tableSmall: "Table small",
    tableStriped: "Table striped",
    tag: "Tag",
    templates: "Templates",
    text: "Text",
    textAlignment: "Text alignment",
    textColor: "Text color",
    thumbnail: "Thumbnail",
    top: "Top",
    verticalHeader: "Vertical header",
    width: "Width",
    yes: "Yes"
}
