tinymce.addI18n("en", {
    "Add col after": "Add column after",
    "Add col before": "Add column before",
    "Add paragraph after": "Add paragraph after",
    "Add paragraph at beginning container": "Add paragraph at the beginning of the current container",
    "Add paragraph at beginning": "Add paragraph at the beginning of the document",
    "Add paragraph at end container": "Add paragraph at the end of the current container",
    "Add paragraph at end": "Add paragraph at the end of the document",
    "Add paragraph before": "Add paragraph before",
    "Add row after": "Add row after",
    "Add row before": "Add row before",
    "Alert": "Alert",
    "Badge": "Badge",
    "Bootstrap Elements": "Bootstrap Elements",
    "Breadcrumb": "Breadcrumb",
    "Button": "Button",
    "Cancel": "Cancel",
    "Card": "Card",
    "column": "column",
    "columns": "columns",
    "Default": "Default",
    "Disable Template Edition": "Disable Template Edition",
    "Edit col": "Edit column",
    "Edit row": "Edit row",
    "Enable Template Edition": "Enable Template Edition",
    "Hide Modal": "Hide Modal",
    "Icon": "Icon",
    "Image": "Image",
    "Insert/Edit Bootstrap Alert": "Insert/Edit Bootstrap Alert",
    "Insert/Edit Bootstrap Badge": "Insert/Edit Bootstrap Badge",
    "Insert/Edit Bootstrap Breadcrumb": "Insert/Edit Bootstrap Breadcrumb",
    "Insert/Edit Bootstrap Button": "Insert/Edit Bootstrap Button",
    "Insert/Edit Bootstrap Card": "Insert/Edit Bootstrap Card",
    "Insert/Edit Bootstrap Icon": "Insert/Edit Bootstrap Icon",
    "Insert/Edit Bootstrap Image": "Insert/Edit Bootstrap Image",
    "Insert/Edit Bootstrap Pager": "Insert/Edit Bootstrap Pager",
    "Insert/Edit Bootstrap Pagination": "Insert/Edit Bootstrap Pagination",
    "Insert/Edit Bootstrap Table": "Insert/Edit Bootstrap Table",
    "Insert/Edit Bootstrap Template": "Insert/Edit Bootstrap Template",
    "Insert/Edit Snippet": "Insert/Edit Snippet",
    "Label": "Label",
    "New column": "New column",
    "New paragraph": "New paragraph",
    "OK": "OK",
    "Pager": "Pager",
    "Pagination": "Pagination",
    "Remove col": "Remove column",
    "Remove row": "Remove row",
    "Screens": "Screens",
    "Show Modal": "Show Modal",
    "Snippet": "Snippet",
    "Table": "Table",
    "Template": "Template"
});
