var lang = {
    addNew: "Ajouter",
    after: "Après",
    alignment: "Alignement",
    altText: "Texte alternatif",
    alwaysResponsive: "Toujours responsive",
    badgepill: "Badge pill",
    before: "Avant",
    bodyHtml: "Body HTML",
    border: "Bordures",
    bordered: "Bordures",
    borderless: "Sans bordures",
    bottom: "Bas",
    browse: "Parcourir",
    button: "Bouton",
    buttonSize: "Taille du bouton",
    buttonStyle: "Style du bouton",
    cancel: "Annuler",
    caption: "Légende",
    cardStyle: "Style de la carte",
    cells: "Cellules",
    center: "Centrer",
    choose: "Choisissez",
    closeButton: "Bouton 'fermer'",
    code: "Code",
    container: "Conteneur",
    current: "Actuel",
    custom: "Personnalisé",
    customColor: "Choisissez une couleur",
    customSize: "Taille personnalisée",
    dark: "Sombre",
    default: "Defaut",
    disabled: "Désactivé",
    disabledWarning: "Les éléments désactivés ne seront pas modifiables dans l'éditeur TinyMce",
    dismissable: "Bouton 'x' pour fermer",
    flip: "Retourner",
    flipBoth: "Retourner des deux côtés",
    flipHorizontal: "Retourner horizontalement",
    flipVertical: "Retourner verticalement",
    floatLeft: "Flottant à gauche",
    floatRight: "Flottant à droite",
    fluidContainer: "Conteneur fluide (largeur 100%)",
    footer: "Footer",
    footerHtml: "Footer HTML",
    header: "Header",
    headerHtml: "Header HTML",
    horizontalHeader: "Header horizontal",
    icon: "Icone",
    iconColor: "Couleur de l'icone",
    icons: "Icones",
    iconSize: "Taille de l'icone",
    iconStyle: "Style de l'icone",
    image: "Image",
    imageOverlay: "Image superposée",
    imageOverlayHtml: "Image superposée HTML",
    imageStyle: "Style de l'image",
    inputWarning: "Les icônes ne sont pas disponibles avec les balises <em>input</em>",
    insert: "Insérer",
    insertAfterContainer: "Insérer après le conteneur actuel",
    insertAfterRow: "Insérer après la rangée actuelle",
    insertBeforeContainer: "Insérer avant le conteneur actuel",
    insertBeforeRow: "Insérer avant la rangée actuelle",
    insertBeginning: "Insérer au début du document",
    insertBeginningContainer: "Insérer au début du conteneur actuel",
    insertCursorPosition: "Insérer à la position du curseur",
    insertEnd: "Insérer à la fin du document",
    insertEndContainer: "Insérer à la fin du conteneur actuel",
    items: "&Eacute;léments",
    large: "Large",
    largeRadius: "Arrondi large",
    left: "Gauche",
    light: "Clair",
    link: "Lien",
    medium: "Moyen",
    mediumRadius: "Arrondi moyen",
    no: "Non",
    noContainer: "Pas de conteneur",
    normalContainer: "Conteneur normal",
    options: "Options",
    others: "Autres",
    outline: "Contour",
    page: "Page",
    pages: "Pages",
    paginationfirst: "Premier",
    paginationlast: "Dernier",
    position: "Position",
    preview: "Aperçu",
    pulse: "Pulse",
    removeImage: "Supprimer l'image",
    reset: "Reset",
    responsive: "Responsive",
    responsiveLg: "Responsive sur les écrans larges et XL",
    responsiveMd: "Responsive sur des écrans moyens et plus grands",
    responsiveSm: "Responsive sur petits écrans et plus grands",
    responsiveXl: "Responsive sur les écrans XL",
    right: "Droite",
    rotate: "Tourner",
    roundedCircle: "Cercle arrondi",
    roundedPill: "Pilule arrondie",
    rowsCols: "Rangées / Colonnes",
    size: "Taille",
    small: "Petit",
    smallRadius: "Petit arrondi",
    snippets: "Snippets",
    spin: "Tournant",
    structure: "Structure",
    style: "Style",
    submit: "Valider",
    tableDark: "Tableau sombre",
    tableEditDisabledInfo: "L'édition de la structure des tableaux est désactivée. Les rangées et les colonnes peuvent être éditées directement dans tinyMce.",
    tableHover: "Tableau survolable",
    tableSmall: "Tableau condensé",
    tableStriped: "Tableau avec rangées alternées",
    tag: "Balise",
    templates: "Templates",
    text: "Texte",
    textAlignment: "Alignement du texte",
    textColor: "Couleur du texte",
    thumbnail: "Vignette",
    top: "Haut",
    verticalHeader: "Header vertical",
    width: "Largeur",
    yes: "Oui"
}
