tinymce.addI18n("fr_FR", {
    "lgtest": "mon cul",
    "Add col after": "Ajouter une colonne après",
    "Add col before": "Ajouter une colonne avant",
    "Add paragraph after": "Ajouter un paragraphe après",
    "Add paragraph at beginning container": "Ajouter un paragraphe au début du conteneur actuel",
    "Add paragraph at beginning": "Ajouter un paragraphe au début du document",
    "Add paragraph at end container": "Ajouter un paragraphe à la fin du conteneur actuel",
    "Add paragraph at end": "Ajouter un paragraphe à la fin du document",
    "Add paragraph before": "Ajouter un paragraphe avant",
    "Add row after": "Ajouter une rangée après",
    "Add row before": "Ajouter une rangée avant",
    "Alert": "Alert",
    "Badge": "Badge",
    "Bootstrap Elements": "Eléments Bootstrap",
    "Breadcrumb": "Breadcrumb",
    "Button": "Button",
    "Cancel": "Annuler",
    "Card": "Card",
    "column": "colonne",
    "columns": "colonnes",
    "Default": "Defaut",
    "Disable Template Edition": "Désactiver l'édition des templates",
    "Edit col": "Editer la colonne",
    "Edit row": "Editer la rangée",
    "Enable Template Edition": "Activer l'édition des templates",
    "Hide Modal": "Cacher le Modal",
    "Icon": "Icone",
    "Image": "Image",
    "Insert/Edit Bootstrap Alert": "Insérer/modifier l'Alerte Bootstrap",
    "Insert/Edit Bootstrap Badge": "Insérer/modifier le Badge Bootstrap",
    "Insert/Edit Bootstrap Breadcrumb": "Insérer/modifier le fil d'Ariane Bootstrap (Breadcrumb)",
    "Insert/Edit Bootstrap Button": "Insérer/modifier le Bouton Bootstrap",
    "Insert/Edit Bootstrap Card": "Insérer/modifier la Carte Bootstrap (Card)",
    "Insert/Edit Bootstrap Icon": "Insérer/modifier l'Icone Bootstrap (Icon)",
    "Insert/Edit Bootstrap Image": "Insérer/modifier l'Image' Bootstrap",
    "Insert/Edit Bootstrap Pager": "Insérer/modifier le Pageur Bootstrap (Pager)",
    "Insert/Edit Bootstrap Pagination": "Insérer/modifier la Pagination Bootstrap",
    "Insert/Edit Bootstrap Table": "Insérer/modifier le Tableau Bootstrap",
    "Insert/Edit Bootstrap Template": "Insérer/modifier le Template Bootstrap",
    "Insert/Edit Snippet": "Insérer/modifier le Snippet",
    "Label": "Label",
    "New column": "Nouvelle colonne",
    "New paragraph": "Nouveau paragraphe",
    "OK": "OK",
    "Pager": "Pager",
    "Pagination": "Pagination",
    "Remove col": "Supprimer la colonne",
    "Remove row": "Supprimer la rangée",
    "Screens": "Ecran",
    "Show Modal": "Afficher le Modal",
    "Snippet": "Snippet",
    "Table": "Tableau",
    "Template": "Template"
});
